version: '3'

vars:
  HOSTNAME: registry.terraform.io
  NAMESPACE: darshan-rambhia
  NAME: docker-compose
  BINARY: terraform-provider-{{.NAME}}
  VERSION: 0.1.0
  OS_ARCH:
    sh: echo "$(go env GOOS)_$(go env GOARCH)"
  BUILD_DIR: ./dist
  INSTALL_DIR: ~/.terraform.d/plugins/{{.HOSTNAME}}/{{.NAMESPACE}}/{{.NAME}}/{{.VERSION}}/{{.OS_ARCH}}

tasks:
  default:
    desc: Build the provider
    cmds:
      - task: build

  build:
    desc: Build the provider binary
    cmds:
      - go build -o {{.BUILD_DIR}}/{{.BINARY}}
    sources:
      - ./**/*.go
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY}}"

  install:
    desc: Install provider locally for testing
    deps: [build]
    cmds:
      - mkdir -p {{.INSTALL_DIR}}
      - cp {{.BUILD_DIR}}/{{.BINARY}} {{.INSTALL_DIR}}/{{.BINARY}}

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  test:unit:
    desc: Run unit tests only
    cmds:
      - go test -v -short ./internal/...

  test:acceptance:
    desc: Run acceptance tests (requires Docker)
    cmds:
      - go test -v ./tests/acceptance/...

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - go test -coverprofile=coverage.out -covermode=atomic ./internal/... ./tests/...
      - go tool cover -func=coverage.out
      - echo "---"
      - go tool cover -func=coverage.out | grep total

  test:coverage:html:
    desc: Generate HTML coverage report
    cmds:
      - go test -coverprofile=coverage.out -covermode=atomic ./internal/...
      - go tool cover -html=coverage.out -o coverage.html
      - 'echo "Coverage report: coverage.html"'

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - terraform fmt -recursive ./examples/ 2>/dev/null || true

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run --timeout=10m ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -rf {{.INSTALL_DIR}}

  docs:
    desc: Generate documentation
    cmds:
      - go generate -tags generate ./...

  deps:
    desc: Download and tidy dependencies
    cmds:
      - go mod download
      - go mod tidy

  debug:
    desc: Run the provider in debug mode
    deps: [build:debug]
    cmds:
      - "{{.BUILD_DIR}}/{{.BINARY}} -debug"

  build:debug:
    desc: Build with debug symbols
    cmds:
      - go build -gcflags="all=-N -l" -o {{.BUILD_DIR}}/{{.BINARY}}

  dev:
    desc: Build and install for local testing
    cmds:
      - task: deps
      - task: build
      - task: install
      - echo "Provider installed to {{.INSTALL_DIR}}"

  release:dry-run:
    desc: Test goreleaser configuration locally (no publish)
    cmds:
      - goreleaser release --snapshot --clean
